### ISSUE TITLE
The name net.connman was not provided by any .service files

### ISSUE THREAD

**Issue by ghost** [StratusFearMe21/listenbrainz-mpv#1]
First of all: thanks for starting this project, I wanted to do something similar in C.

---

I am doing the following steps to 'install' the plugin:
```
# in the "listenbrainz-mpv" folder
rustup override set nightly
cargo build --release
cp ./target/release/liblistenbrainz_mpv.so $HOME/.config/mpv/scripts
```

when run `mpv <filename>`:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: The name net.connman was not provided by any .service files (org.freedesktop.DBus.Error.ServiceUnknown)', src/lib.rs:503:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

and `RUST_BACKTRACE=full mpv <filename>`:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: The name net.connman was not provided by any .service files (org.freedesktop.DBus.Error.ServiceUnknown)', src/lib.rs:503:18
stack backtrace:
   0:     0x7fa09bcf8b10 - <unknown>
   1:     0x7fa09bc4456e - <unknown>
   2:     0x7fa09bcd4804 - <unknown>
   3:     0x7fa09bcfa31f - <unknown>
   4:     0x7fa09bcf9f1f - <unknown>
   5:     0x7fa09bcfafd9 - <unknown>
   6:     0x7fa09bcfaa84 - <unknown>
   7:     0x7fa09bcfa9ec - <unknown>
   8:     0x7fa09bcfa9c1 - <unknown>
   9:     0x7fa09bc1ce42 - <unknown>
  10:     0x7fa09bc1d2a2 - <unknown>
  11:     0x7fa09bc3fa26 - mpv_open_cplugin
  12:     0x562febdc92f1 - <unknown>
  13:     0x562febdc8d41 - <unknown>
  14:     0x562febdc91b9 - <unknown>
  15:     0x7fa0c78a7fd4 - <unknown>
  16:     0x7fa0c792866c - <unknown>
  17:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
```

I don't know if I'm failing in the build or if it's a code error.
I couldn't find another plugin in RUST to guide me.

Many thanks.

**Comment by ghost** [comment]
It is also missing to specify that in the 'listenbrainz-cache-path' there has to be a directory called 'listenbrainz' because the script does not generate it.

**Comment by ghost** [comment]
[SOLVED] It was missing to install 'connman'

**Comment by StratusFearMe21** [comment]
@otrocodigo, connman is no longer a hard dependency of this project, and I suggest you uninstall it, as it probably conflicts with whatever network manager your distro came with. If you compiled my plugin with `--features connman`, you can just ommit that and the plugin will work as normal.

**Comment by ghost** [comment]
nice. i just remove _connman_ and recompiled the latest version of the plugin :100:
